products = [
    {
        "_id": "1",
        "name": "Showcase Exclusif : EL Grande TOTO  ",
        "image": "/images/toto.jpg",
        "image2": "/images/toto2.jpg",
        "image3": "/images/toto3.jpg",
        "description": "L'artiste le plus écouté au Maroc et dans le monde arabe",
        # "date": "19/02/2023",
        "category": "RAP",
        "localisation": "CASABLANCA , MA",
        "price": 400,
        "countInStock": 20,
        "dateShow": "8:00AM - 5:30PM",
        "numReviews": 12,
        'rating': 4.5,
    },
    {
        "_id": "2",
        "name": "Showcase Exclusif :  Draganov",
        "image": "/images/draga.jpg",
        "image2": "/images/draga2.jpg",
        "image3": "https://images.genius.com/411b3c96ba6963a19349f59c549dbfc6.1000x1000x1.jpg",
        "description":
        "Passionné par la culture urbaine, il crée son premier groupe en 2008 «The Kings 48», avec ses amis et musiciens Adil Boudebouz et Dj Adam. Ils sortent ainsi un premier maxi nommé «System Dawla». C'est en 2010 que Draganov décide de continuer en solo et sort son album «Zidou Lgoudam». De 2008 jusqu'en 2012, il participe à plusieurs événements tels que le festival international du rai (2012), le festival des enfants handicapés (2010) et le festival «Non à la drogue» (en 2009). Ce n'est qu'en 2013 qu'il sort son tout premier clip «7yat 9ssira». Ce dernier a été bien accueilli sur la scène rap marocaine en marquant plus que 100 000 vues sur Youtube. Mr. Draganov sort ensuite le mixe tape «Hall Of Fame» qui crée le buzz. S'en suivent plusieurs concerts à Oujda, notamment le «Moroccan 8 Mile», en collaboration avec le groupe Shayfeen. Mr. ",
        # "date": "19/09/2023",
        "category": "RAP",
        "localisation": "ORLANDO,USA",
        "price": 599.99,
        "countInStock": 7,
        "dateShow": "5:00AM - 5:30PM",
        "numReviews": 8,

        'rating': 2.5, },
    {
        "_id": "3",
        "name": "DIZZY DROS EN CONCERT",
        "image": "/images/DizzyDross.jpg",
        "image2": "/images/Dizzy3.png",
        "image3": "https://www.belpresse.com/wp-content/uploads/2021/09/Screenshot_20210912_101405.jpg",
        "description":
        "Le fameux DIZZY DROS et la talentueuse Kawtar SADIK vous donnent rendez-vous sur scène à l'ISCAE Casablanca le 14 mai à 21h ! A l'occasion de l'organisation de la 22e édition des Olympiades de l'ISCAE Casablanca, le rappeur, auto-compositeur, producteur DIZZY DROS et la compositrice, chanteuse et DJ Kawtar SADIK se produit sur scène le 14 mai à l'ISCAE même. Ne ratez pas cette occasion inédite et ravivez la flamme de la musique en chacun d'entre nous ! Rendez-vous le 14 mai !",
        # "date": "22/07/2023",
        "category": "RAP",
        "localisation": "RABAT,MA",
        "price": 929.99,
        "countInStock": 5,
        "dateShow": "8:00AM - 4:30PM",
        "numReviews": 12,
        'rating': 4.5,
    },
    {
        "_id": "4",
        "name": "Sfera Ebasta",
        "image": "/images/sferaebasta.jpg",
        "image2": "https://wallpaperaccess.com/full/2754333.jpg",
        "image3": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Sfera_Ebbasta_Rapper.jpg/800px-Sfera_Ebbasta_Rapper.jpg",
        "description":
        "Gionata Boschetti, known professionally as Sfera Ebbasta, is an Italian rapper. Ebbasta rose to prominence after the release of XDVR, recorded with the collaboration of record producer Charlie Charles and DEACC which achieved commercial success in Italy",
        # "date": "23/04/2023",
        "category": "RAP",
        "localisation": "ROME,IT",
        "price": 399.99,
        "countInStock": 11,
        "dateShow": "8:00AM - 5:00PM",
        "numReviews": 12,
        'rating': 5,
    },
    {
        "_id": "5",
        "name": "Concert Live : Shayfeen",
        "image": "https://images.genius.com/be62059193b81b1960e0214f6fd854f1.1000x1000x1.jpg",
        "image2": "https://dice-media.imgix.net/events/shayfeen-manal-1st-aug-the-jazz-cafe-london-tickets/landscape-original.jpg?rect=202%2C11%2C895%2C531&w=1300&h=630&auto=compress",
        "image3": "https://images.genius.com/5ad739f4ae682e2b707d14a4ba1df524.960x960x1.jpg",
        "description": "Shayfeen est un groupe de rap marocain composé de Chouaib Ribati (Shobee) et Abdessamad Lamriq (Small X). ",
        # "date": "19/10/2023",
        "category": "RAP",
        "localisation": "SAFI , MA",
        "price": 499,
        "countInStock": 7,
        "dateShow": "8:20AM - 5:30PM",
        "numReviews": 10,
        'rating': 4,
    },
    {
        "_id": "6",
        "name": "7liwa",
        "image": "https://yt3.ggpht.com/3ObVRbS2pHnOJ5lan-I-J-MKssC2t3K8iZuxjZNSQGgs1RjrGq9kEj8pYT9DUjZ5_X2NoHg1=s900-c-k-c0x00ffffff-no-rj",
        "image2": "https://i.ytimg.com/vi/jmBiK4pG1jg/maxresdefault.jpg",
        "image3": "https://yt3.ggpht.com/3ObVRbS2pHnOJ5lan-I-J-MKssC2t3K8iZuxjZNSQGgs1RjrGq9kEj8pYT9DUjZ5_X2NoHg1=s900-c-k-c0x00ffffff-no-rj",
        "description":
        "Showcase exclusif du rappeur 7liwa à l'occasion du lancement de son premier album #Lastreet . la soirée aura lieu le 07 décembre 2019 à Versace Lounge Marrakech à partir de 19h00 .",
        # "date": "18/02/2023",
        "category": "RAP",
        "localisation": "CASABLANCA,MA",
        "price": 29.99,
        "countInStock": 0,
        "dateShow": "10:00AM - 5:30PM",
        "numReviews": 12,
        'rating': 2,
    },
    {
        "_id": "7",
        "name": "Don Big",
        "image": "/images/DonBig.jpg",
        "image2": "/images/big-cover.jpg",
        "image3": "https://scontent.fcmn3-1.fna.fbcdn.net/v/t1.6435-9/106919080_10163993600480296_3282971582008522466_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=9267fe&_nc_eui2=AeETilWD2vbKmkoq5ky0pS6pbLOsuP4FPtdss6y4_gU-12guEDd7SbfHBazKcn6GuTN9GYJmGmBZ1shl_Kuom6Q-&_nc_ohc=-Z6ntm8FrYIAX8cj3S_&_nc_ht=scontent.fcmn3-1.fna&oh=00_AT-CmaiA8JTR3Nv1PUdtVsWSXbvnoRwQm54LWfuTGs120A&oe=62D910F9",
        "description":
        "Showcase exclusif du rappeur 7liwa à l'occasion du lancement de son premier album #Lastreet . la soirée aura lieu le 07 décembre 2019 à Versace Lounge Marrakech à partir de 19h00 .",
        # "date": "19/03/2023",
        "category": "RAP",
        "localisation": "CASABLANCA,MA",
        "price": 29.99,
        "countInStock": 0,
        "dateShow": "8:00AM - 8:30PM",
        "numReviews": 12,
        'rating': 3.5,
    },
]
