# Generated by Django 4.0.5 on 2022-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateShow',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
    ]
