# Generated by Django 4.0.5 on 2022-06-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_dateshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
