# Generated by Django 4.0.5 on 2022-07-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_image_product_image2_product_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxPrice',
            new_name='itemsPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
